repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  gwt_user: com.google.gwt:gwt-user:jar:2.6.0-rc1
  gwt_dev: com.google.gwt:gwt-dev:jar:2.6.0-rc1

  # Mocking library used in tests
  mockito: org.mockito:mockito-all:jar:1.8.5
